FROM centos:latest
RUN cd /etc/yum.repos.d/
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
RUN yum update -y && yum install java-1.8.0-openjdk -y
RUN mkdir /opt/tomcat
WORKDIR /opt/tomcat
ADD https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.71/bin/apache-tomcat-9.0.71.tar.gz  /opt/tomcat
RUN tar -xvzf apache-tomcat-9.0.71.tar.gz 
RUN mv apache-tomcat-9.0.71/* /opt/tomcat
COPY ./tomcat-users.xml /opt/tomcat/conf/tomcat-users.xml
COPY ./context.xml /opt/tomcat/webapps/manager/META-INF/context.xml
RUN sh -c 'chmod +x /opt/tomcat/bin/*.sh'
EXPOSE 8080
CMD ["/opt/tomcat/bin/catalina.sh","run"]

